# Generated by Django 6.0.3 on 2026-03-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('조식', '조식'), ('중식', '중식'), ('석식', '석식'), ('기타', '기타')], max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target_date', 'meal_type'), name='unique_diet_plan')],
            },
        ),
        migrations.CreateModel(
            name='DietMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_menus', to='meals.dietplan')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.menu')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('diet_plan', 'menu'), name='unique_diet_menu')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_amount', models.DecimalField(decimal_places=2, help_text='1인분 소요량', max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='inventory.ingredient')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='meals.menu')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('menu', 'ingredient'), name='unique_recipe_ingredient')],
            },
        ),
    ]
