# Generated by Django 6.0.3 on 2026-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='메뉴 분류'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='meal_type',
            field=models.CharField(choices=[('조식', '조식'), ('중식', '중식'), ('석식', '석식'), ('기타', '기타')], max_length=10, verbose_name='끼니'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='target_date',
            field=models.DateField(verbose_name='식단 날짜'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='메뉴명'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='required_amount',
            field=models.DecimalField(decimal_places=2, help_text='1인분 소요량 (예: 0.15)', max_digits=10),
        ),
    ]
