# Generated by Django 6.0.3 on 2026-04-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_menu_category_alter_dietplan_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='headcount',
            field=models.IntegerField(default=0, verbose_name='식수(목표/당일인원)'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='is_served',
            field=models.BooleanField(default=False, verbose_name='재고 차감 완료 여부'),
        ),
    ]
