# Generated by Django 6.0.3 on 2026-03-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("NUTRITIONIST", "Nutritionist"),
                    ("SUPPLIER", "Supplier"),
                ],
                default="NUTRITIONIST",
                max_length=20,
            ),
        ),
    ]
