# Generated by Django 6.0.3 on 2026-03-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='대분류'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='금액'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='yearly_demand',
            field=models.IntegerField(blank=True, null=True, verbose_name='연간예상소요량'),
        ),
    ]
