# Generated by Django 6.0.3 on 2026-03-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(default="ea", max_length=20),
        ),
    ]
