# Generated by Django 6.0.3 on 2026-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_ingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
