# Generated by Django 6.0.3 on 2026-03-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient_category_ingredient_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='규격'),
        ),
    ]
