# Generated by Django 6.0.3 on 2026-04-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='현재 재고량'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='변동 사유'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='log_type',
            field=models.CharField(choices=[('입고', '입고'), ('출고', '출고'), ('폐기', '폐기'), ('조정', '조정')], max_length=10),
        ),
    ]
