# Generated by Django 6.0.3 on 2026-04-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_ingredient_current_stock_inventorylog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='current_stock',
        ),
    ]
