# Generated by Django 6.0.3 on 2026-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_ingredient_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='식품 설명'),
        ),
    ]
