# Generated by Django 6.0.3 on 2026-04-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('배송중', '배송중'), ('배송완료', '배송완료')], default='대기', max_length=10),
        ),
    ]
