# Generated by Django 6.0.3 on 2026-05-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_ingredient_current_stock'),
        ('procurement', '0002_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_ingredient',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='target_date',
            field=models.DateField(blank=True, null=True, verbose_name='요청일(식단일)'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'ingredient', 'target_date'), name='unique_order_ingredient_date'),
        ),
    ]
