# Generated by Django 6.0.3 on 2026-05-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_ingredient_current_stock'),
        ('procurement', '0003_remove_orderitem_unique_order_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_ingredient_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meal_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='끼니 구문'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'ingredient', 'target_date', 'meal_type'), name='unique_order_ingredient_date_meal'),
        ),
    ]
