# Generated by Django 6.0.3 on 2026-03-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_count', models.IntegerField()),
                ('reference_data', models.JSONField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('diet_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='meals.dietplan')),
            ],
        ),
    ]
