# Generated by Django 6.0.3 on 2026-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendancePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateField(verbose_name="예측 날짜")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "조식"),
                            ("lunch", "중식"),
                            ("dinner", "석식"),
                        ],
                        max_length=20,
                        verbose_name="끼니",
                    ),
                ),
                ("predicted_count", models.IntegerField(verbose_name="예측 인원")),
                ("model_name", models.CharField(max_length=100, verbose_name="모델명")),
                (
                    "input_features",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="입력 feature"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-prediction_date", "-created_at"],
            },
        ),
    ]
